/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Jeovani Thomazini
 */
public class JFMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public JFMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        btnCurso = new javax.swing.JPanel();
        jpCursorCurso = new javax.swing.JPanel();
        jlCurso = new javax.swing.JLabel();
        btnDisciplinas = new javax.swing.JPanel();
        jpCursorDisciplina = new javax.swing.JPanel();
        jlDisciplina = new javax.swing.JLabel();
        btnProfessores = new javax.swing.JPanel();
        jpCursorProfessores = new javax.swing.JPanel();
        jlProfessores = new javax.swing.JLabel();
        btnAlunos = new javax.swing.JPanel();
        jpCursorAlunos = new javax.swing.JPanel();
        jlAlunos = new javax.swing.JLabel();
        jpShow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(71, 120, 197));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setBackground(new java.awt.Color(23, 35, 51));

        btnCurso.setBackground(new java.awt.Color(41, 57, 80));
        btnCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCursoMousePressed(evt);
            }
        });

        jpCursorCurso.setBackground(new java.awt.Color(255, 255, 255));
        jpCursorCurso.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout jpCursorCursoLayout = new javax.swing.GroupLayout(jpCursorCurso);
        jpCursorCurso.setLayout(jpCursorCursoLayout);
        jpCursorCursoLayout.setHorizontalGroup(
            jpCursorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpCursorCursoLayout.setVerticalGroup(
            jpCursorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlCurso.setForeground(new java.awt.Color(255, 255, 255));
        jlCurso.setText("Cursos");

        javax.swing.GroupLayout btnCursoLayout = new javax.swing.GroupLayout(btnCurso);
        btnCurso.setLayout(btnCursoLayout);
        btnCursoLayout.setHorizontalGroup(
            btnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCursoLayout.createSequentialGroup()
                .addComponent(jpCursorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlCurso)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCursoLayout.setVerticalGroup(
            btnCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCursorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addGroup(btnCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCurso)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnDisciplinas.setBackground(new java.awt.Color(23, 35, 51));
        btnDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDisciplinasMousePressed(evt);
            }
        });

        jpCursorDisciplina.setBackground(new java.awt.Color(255, 255, 255));
        jpCursorDisciplina.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout jpCursorDisciplinaLayout = new javax.swing.GroupLayout(jpCursorDisciplina);
        jpCursorDisciplina.setLayout(jpCursorDisciplinaLayout);
        jpCursorDisciplinaLayout.setHorizontalGroup(
            jpCursorDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpCursorDisciplinaLayout.setVerticalGroup(
            jpCursorDisciplinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        jlDisciplina.setText("Disciplinas");

        javax.swing.GroupLayout btnDisciplinasLayout = new javax.swing.GroupLayout(btnDisciplinas);
        btnDisciplinas.setLayout(btnDisciplinasLayout);
        btnDisciplinasLayout.setHorizontalGroup(
            btnDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDisciplinasLayout.createSequentialGroup()
                .addComponent(jpCursorDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlDisciplina)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        btnDisciplinasLayout.setVerticalGroup(
            btnDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCursorDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addGroup(btnDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDisciplina)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnProfessores.setBackground(new java.awt.Color(23, 35, 51));
        btnProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProfessoresMousePressed(evt);
            }
        });

        jpCursorProfessores.setBackground(new java.awt.Color(255, 255, 255));
        jpCursorProfessores.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout jpCursorProfessoresLayout = new javax.swing.GroupLayout(jpCursorProfessores);
        jpCursorProfessores.setLayout(jpCursorProfessoresLayout);
        jpCursorProfessoresLayout.setHorizontalGroup(
            jpCursorProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpCursorProfessoresLayout.setVerticalGroup(
            jpCursorProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlProfessores.setForeground(new java.awt.Color(255, 255, 255));
        jlProfessores.setText("Professores");

        javax.swing.GroupLayout btnProfessoresLayout = new javax.swing.GroupLayout(btnProfessores);
        btnProfessores.setLayout(btnProfessoresLayout);
        btnProfessoresLayout.setHorizontalGroup(
            btnProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProfessoresLayout.createSequentialGroup()
                .addComponent(jpCursorProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlProfessores)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        btnProfessoresLayout.setVerticalGroup(
            btnProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCursorProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addGroup(btnProfessoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlProfessores)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnAlunos.setBackground(new java.awt.Color(23, 35, 51));
        btnAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAlunosMousePressed(evt);
            }
        });

        jpCursorAlunos.setBackground(new java.awt.Color(255, 255, 255));
        jpCursorAlunos.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout jpCursorAlunosLayout = new javax.swing.GroupLayout(jpCursorAlunos);
        jpCursorAlunos.setLayout(jpCursorAlunosLayout);
        jpCursorAlunosLayout.setHorizontalGroup(
            jpCursorAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpCursorAlunosLayout.setVerticalGroup(
            jpCursorAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jlAlunos.setText("Alunos");

        javax.swing.GroupLayout btnAlunosLayout = new javax.swing.GroupLayout(btnAlunos);
        btnAlunos.setLayout(btnAlunosLayout);
        btnAlunosLayout.setHorizontalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlunosLayout.createSequentialGroup()
                .addComponent(jpCursorAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlAlunos)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        btnAlunosLayout.setVerticalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCursorAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addGroup(btnAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAlunos)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 520));

        jpShow.setBackground(new java.awt.Color(71, 120, 197));
        jpShow.setName(""); // NOI18N

        javax.swing.GroupLayout jpShowLayout = new javax.swing.GroupLayout(jpShow);
        jpShow.setLayout(jpShowLayout);
        jpShowLayout.setHorizontalGroup(
            jpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jpShowLayout.setVerticalGroup(
            jpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jpShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 790, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCursoMousePressed
        ClickButon(btnCurso,jpCursorCurso);
    }//GEN-LAST:event_btnCursoMousePressed

    private void btnDisciplinasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisciplinasMousePressed
        ClickButon(btnDisciplinas,jpCursorDisciplina);        
    }//GEN-LAST:event_btnDisciplinasMousePressed

    private void btnProfessoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfessoresMousePressed
        ClickButon(btnProfessores,jpCursorProfessores);
    }//GEN-LAST:event_btnProfessoresMousePressed

    private void btnAlunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlunosMousePressed
        ClickButon(btnAlunos,jpCursorAlunos);
    }//GEN-LAST:event_btnAlunosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFMain frame = new JFMain();
		frame.setVisible(true);					
            }
        });
    }
    
    private void ClickButon(JPanel Buton, JPanel Cursor){
        resetAllButons();
        setColor(Buton);
        setOpaque(Cursor);
    }
    
    private void setColor(JPanel Panel){
        Panel.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel Panel){
        Panel.setBackground(new Color(23,35,51));
    }
    
    private void setOpaque(JPanel Panel){
        Panel.setOpaque(true);
    }
    
    private void resetOpaque(JPanel Panel){
        Panel.setOpaque(false);
    }
    
    private void resetAllButons(){
        resetColor(btnCurso);
        resetColor(btnProfessores);
        resetColor(btnAlunos);
        resetColor(btnDisciplinas);
        resetOpaque(jpCursorCurso);
        resetOpaque(jpCursorDisciplina);
        resetOpaque(jpCursorProfessores);
        resetOpaque(jpCursorAlunos);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAlunos;
    private javax.swing.JPanel btnCurso;
    private javax.swing.JPanel btnDisciplinas;
    private javax.swing.JPanel btnProfessores;
    private javax.swing.JLabel jlAlunos;
    private javax.swing.JLabel jlCurso;
    private javax.swing.JLabel jlDisciplina;
    private javax.swing.JLabel jlProfessores;
    private javax.swing.JPanel jpCursorAlunos;
    private javax.swing.JPanel jpCursorCurso;
    private javax.swing.JPanel jpCursorDisciplina;
    private javax.swing.JPanel jpCursorProfessores;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpShow;
    // End of variables declaration//GEN-END:variables
}
